### ISSUE TITLE
Disable Work button if timer is 00:01

### ISSUE THREAD

**Issue by emilhem** [osanwe/saildoro#2]
So, when using saildoro the timer tends to stop at 00:01. If you accidentally press Work when it is 00:01 it leads to the addition of a pomodoro for the active task since the timer reaches 00:00 instantly.

Now I have an extra pomodoro because of this bug. So this leads to my other issue that is reported soon.

**Comment by emilhem** [comment]
By fixing issue #3 you can fix accidentally added pomodoros created by this issue.

**Comment by osanwe** [comment]
Fixed.

**Comment by osanwe** [comment]
Fixed.

**Comment by osanwe** [comment]
Fixed.

**Comment by osanwe** [comment]
Fixed.
