### ISSUE TITLE
Timer stops whenever screen is off

### ISSUE THREAD

**Issue by emilhem** [osanwe/saildoro#4]
Pretty much what the title says.

This isn't explain in the README.md nor in the app which is why I'm bringing it up.

My assumption is that Sailfish sleeps the app, but then how can apps such as alarm work while the phone is "sleeping"? Maybe the app should record the button press of the work as a timestamp in the database and set an event for the time when the timer runs out. This way when the sailfish "unsleeps" the app it can redraw the timer at the correct time using the current time and the timestamp.

**Comment by osanwe** [comment]
Fixed.

**Comment by TzwennD** [comment]
Maybe I am blind, but could it be that the code here is not up-to-date?
